window.ROConfigLocal = {  
    development: true,  
    remoteClient: 'https://grf.robrowser.com/',  
    servers: [  
        {
            display: 'Your Local Server[PRE]',
            desc: '2013 demo server',
            address: '127.0.0.1',
            port: 6900,
            version: 25,
            langtype: 12,
            packetver: 20130618,
            renewal: false,
            worldMapSettings: { episode: 12 },
            packetKeys: false,
            socketProxy: 'ws://localhost:5999',
            remoteClient: '/remote-client/',
            adminList: []
        },
        {
            display: 'Your Local Server[RE]',
            desc: '2025 demo server',
            address: '127.0.0.1',
            port: 6900,
            version: 55,
            langtype: 12,
            packetver: 20250618,
            renewal: true,
            worldMapSettings: { episode: 21 },
            packetKeys: false,
            socketProxy: 'ws://localhost:5999',
            remoteClient: '/remote-client/',
            adminList: []
        }, 
        {  
            display: 'NiktoutRO Chaos',  
            desc: 'NiktoutRO Chaos [100k/100k/10%]',  
            address: 'chaos.niktoutro.com',  
            port: 6905,  
            version: 55,  
            langtype: 1,  
            packetver: 20151104,  
            renewal: true,  
            socketProxy: 'wss://classicweb.niktoutro.com:5999',  
            remoteClient: 'https://classicweb.niktoutro.com/chaosclient/',  
            registrationweb: 'https://niktoutro.com/?module=account&action=create',  
            packetKeys: true,  
            adminList: [2000002]  
        }  
    ],  
    packetDump: false,  
    skipServerList: true,  
    skipIntro: false,  
    aura: {},  
    autoLogin: [],  
    BGMFileExtension: ['mp3'],  
    calculateHash: false,  
    CameraMaxZoomOut: 5,  
    charBlockSize: 0,  
    clientHash: null,  
    clientVersionMode: 'PacketVer',  
    disableConsole: false,  
    enableAchievements: false,
    enableBank: false,  
    enableCashShop: false,  
    enableCheckAttendance: false,  
    enableDmgSuffix: false,  
    enableHomunAutoFeed: false,  
    enableMapName: false,  
    FirstPersonCamera: false,  
    grfList: null,  
    hashFiles: [],  
    loadLua: false,  
    onReady: null,  
    plugins: {},  
    registrationweb: '',  
    saveFiles: true,  
    ThirdPersonCamera: false,  
    transitionDuration: 500
};
