/**
 * DB/Skills/SkillUnit.js
 *
 * Zone effects
 *
 * This file is part of ROBrowser, (http://www.robrowser.com/).
 *
 * @author Vincent Thibault
 */

define(['./SkillUnitConst', './SkillConst'], function( SU, SK )
{
	'use strict';
	
	var SkillUnit = {};

	SkillUnit[SU.UNT_SAFETYWALL] =			SK.MG_SAFETYWALL;
	SkillUnit[SU.UNT_FIREWALL] =			SK.MG_FIREWALL;
	SkillUnit[SU.UNT_WARP_WAITING] =		SK.AL_WARP;
	SkillUnit[SU.UNT_WARP_ACTIVE] =			SK.AL_WARP;
	SkillUnit[SU.UNT_SANCTUARY] =			SK.PR_SANCTUARY;
	SkillUnit[SU.UNT_MAGNUS] =				SK.PR_MAGNUS;
	SkillUnit[SU.UNT_PNEUMA] =				SK.AL_PNEUMA;
	SkillUnit[SU.UNT_FIREPILLAR_WAITING] =	SK.WZ_FIREPILLAR;
	SkillUnit[SU.UNT_ICEWALL] =				SK.WZ_ICEWALL;
	SkillUnit[SU.UNT_QUAGMIRE] =			SK.WZ_QUAGMIRE;
	SkillUnit[SU.UNT_BLASTMINE] =			SK.HT_BLASTMINE;
	SkillUnit[SU.UNT_SKIDTRAP] =			SK.HT_SKIDTRAP;
	SkillUnit[SU.UNT_ANKLESNARE] =			SK.HT_ANKLESNARE;
	SkillUnit[SU.UNT_VENOMDUST] =			SK.AS_VENOMDUST;
	SkillUnit[SU.UNT_LANDMINE] =			SK.HT_LANDMINE;
	SkillUnit[SU.UNT_SHOCKWAVE] =			SK.HT_SHOCKWAVE;
	SkillUnit[SU.UNT_SANDMAN] =				SK.HT_SANDMAN;
	SkillUnit[SU.UNT_FLASHER] =				SK.HT_FLASHER;
	SkillUnit[SU.UNT_FREEZINGTRAP] =		SK.HT_FREEZINGTRAP;
	SkillUnit[SU.UNT_CLAYMORETRAP] =		SK.HT_CLAYMORETRAP;
	SkillUnit[SU.UNT_TALKIEBOX] =			SK.HT_TALKIEBOX;
	SkillUnit[SU.UNT_VOLCANO] =				SK.SA_VOLCANO;
	SkillUnit[SU.UNT_DELUGE] =				SK.SA_DELUGE;
	SkillUnit[SU.UNT_VIOLENTGALE] =			SK.SA_VIOLENTGALE;
	SkillUnit[SU.UNT_LANDPROTECTOR] =		SK.SA_LANDPROTECTOR;
	SkillUnit[SU.UNT_LULLABY] =				SK.BD_LULLABY;
	SkillUnit[SU.UNT_RICHMANKIM] =			SK.BD_RICHMANKIM;
	SkillUnit[SU.UNT_ETERNALCHAOS] =		SK.BD_ETERNALCHAOS;
	SkillUnit[SU.UNT_DRUMBATTLEFIELD] =		SK.BD_DRUMBATTLEFIELD;
	SkillUnit[SU.UNT_RINGNIBELUNGEN] =		SK.BD_RINGNIBELUNGEN;
	SkillUnit[SU.UNT_ROKISWEIL] =			SK.BD_ROKISWEIL;
	SkillUnit[SU.UNT_INTOABYSS] =			SK.BD_INTOABYSS;
	SkillUnit[SU.UNT_SIEGFRIED] =			SK.BD_SIEGFRIED;
	SkillUnit[SU.UNT_DISSONANCE] =			SK.BA_DISSONANCE;
	SkillUnit[SU.UNT_WHISTLE] =				SK.BA_WHISTLE;
	SkillUnit[SU.UNT_ASSASSINCROSS] =		SK.BA_ASSASSINCROSS;
	SkillUnit[SU.UNT_POEMBRAGI] =			SK.BA_POEMBRAGI;
	SkillUnit[SU.UNT_APPLEIDUN] =			SK.BA_APPLEIDUN;
	SkillUnit[SU.UNT_UGLYDANCE] =			SK.DC_UGLYDANCE;
	SkillUnit[SU.UNT_HUMMING] =				SK.DC_HUMMING;
	SkillUnit[SU.UNT_DONTFORGETME] =		SK.DC_DONTFORGETME;
	SkillUnit[SU.UNT_FORTUNEKISS] =			SK.DC_FORTUNEKISS;
	SkillUnit[SU.UNT_SERVICEFORYOU] =		SK.DC_SERVICEFORYOU;
	SkillUnit[SU.UNT_GRAFFITI] =			SK.RG_GRAFFITI;
	SkillUnit[SU.UNT_DEMONSTRATION] =		SK.AM_DEMONSTRATION;
	SkillUnit[SU.UNT_GOSPEL] =				SK.PA_GOSPEL;
	SkillUnit[SU.UNT_BASILICA] =			SK.HP_BASILICA;
	SkillUnit[SU.UNT_MOONLIT] =				SK.CG_MOONLIT;
	SkillUnit[SU.UNT_FOGWALL] =				SK.PF_FOGWALL;
	SkillUnit[SU.UNT_SPIDERWEB] =			SK.PF_SPIDERWEB;
	SkillUnit[SU.UNT_GRAVITATION] =			SK.HW_GRAVITATION;
	SkillUnit[SU.UNT_HERMODE] =				SK.CG_HERMODE;
	SkillUnit[SU.UNT_SUITON] =				SK.NJ_SUITON;
	SkillUnit[SU.UNT_TATAMIGAESHI] =		SK.NJ_TATAMIGAESHI;
	SkillUnit[SU.UNT_KAEN] =				SK.NJ_KAENSIN;
	SkillUnit[SU.UNT_GROUNDDRIFT_WIND] =	SK.GS_GROUNDDRIFT;
	SkillUnit[SU.UNT_GROUNDDRIFT_WATER] =	SK.GD_LEADERSHIP;
	SkillUnit[SU.UNT_GROUNDDRIFT_FIRE] =	SK.GD_GLORYWOUNDS;
	SkillUnit[SU.UNT_DEATHWAVE ] =			SK.GD_SOULCOLD;
	SkillUnit[SU.UNT_WATERATTACK ] =		SK.GD_HAWKEYES;
	SkillUnit[SU.UNT_EVILLAND] =			SK.NPC_EVILLAND;
	SkillUnit[SU.UNT_EPICLESIS] =			SK.AB_EPICLESIS;
	SkillUnit[SU.UNT_EARTHSTRAIN] =			SK.WL_EARTHSTRAIN;
	SkillUnit[SU.UNT_MANHOLE] =				SK.SC_MANHOLE;
	SkillUnit[SU.UNT_DIMENSIONDOOR] =		SK.SC_DIMENSIONDOOR;
	SkillUnit[SU.UNT_CHAOSPANIC] =			SK.SC_CHAOSPANIC;
	SkillUnit[SU.UNT_MAELSTROM] =			SK.SC_MAELSTROM;
	SkillUnit[SU.UNT_BLOODYLUST] =			SK.SC_BLOODYLUST;
	SkillUnit[SU.UNT_FEINTBOMB] =			SK.SC_FEINTBOMB;
	SkillUnit[SU.UNT_MAGENTATRAP] =			SK.RA_MAGENTATRAP;
	SkillUnit[SU.UNT_COBALTTRAP] =			SK.RA_COBALTTRAP;
	SkillUnit[SU.UNT_MAIZETRAP] =			SK.RA_MAIZETRAP;
	SkillUnit[SU.UNT_VERDURETRAP] =			SK.RA_VERDURETRAP;
	SkillUnit[SU.UNT_FIRINGTRAP] =			SK.RA_FIRINGTRAP;
	SkillUnit[SU.UNT_ICEBOUNDTRAP] =		SK.RA_ICEBOUNDTRAP;
	SkillUnit[SU.UNT_ELECTRICSHOCKER] =		SK.RA_ELECTRICSHOCKER;
	SkillUnit[SU.UNT_CLUSTERBOMB] =			SK.RA_CLUSTERBOMB;
	SkillUnit[SU.UNT_REVERBERATION] =		SK.WM_REVERBERATION;
	SkillUnit[SU.UNT_SEVERE_RAINSTORM] =	SK.WM_SEVERE_RAINSTORM;
	SkillUnit[SU.UNT_FIREWALK] =			SK.SO_FIREWALK;
	SkillUnit[SU.UNT_ELECTRICWALK] =		SK.SO_ELECTRICWALK;
	SkillUnit[SU.UNT_NETHERWORLD] =			SK.WM_POEMOFNETHERWORLD;
	SkillUnit[SU.UNT_PSYCHIC_WAVE] =		SK.SO_PSYCHIC_WAVE;
	SkillUnit[SU.UNT_CLOUD_KILL] =			SK.SO_CLOUD_KILL;
	SkillUnit[SU.UNT_POISONSMOKE] =			SK.GC_POISONSMOKE;
	SkillUnit[SU.UNT_NEUTRALBARRIER] =		SK.NC_NEUTRALBARRIER;
	SkillUnit[SU.UNT_STEALTHFIELD] =		SK.NC_STEALTHFIELD;
	SkillUnit[SU.UNT_WARMER] =				SK.SO_WARMER;
	SkillUnit[SU.UNT_THORNS_TRAP] =			SK.GN_THORNS_TRAP;
	SkillUnit[SU.UNT_WALLOFTHORN] =			SK.GN_WALLOFTHORN;
	SkillUnit[SU.UNT_DEMONIC_FIRE] =					SK.GN_DEMONIC_FIRE;
	SkillUnit[SU.UNT_FIRE_EXPANSION_SMOKE_POWDER] =		SK.GN_FIRE_EXPANSION_SMOKE_POWDER;
	SkillUnit[SU.UNT_FIRE_EXPANSION_TEAR_GAS] =			SK.GN_FIRE_EXPANSION_TEAR_GAS;
	SkillUnit[SU.UNT_HELLS_PLANT ] =			SK.GN_HELLS_PLANT;
	SkillUnit[SU.UNT_VACUUM_EXTREME] =		SK.SO_VACUUM_EXTREME;
	SkillUnit[SU.UNT_BANDING] =				SK.LG_BANDING;
	SkillUnit[SU.UNT_FIRE_MANTLE] =			SK.EL_FIRE_MANTLE;
	SkillUnit[SU.UNT_WATER_BARRIER] =		SK.EL_WATER_BARRIER;
	SkillUnit[SU.UNT_ZEPHYR] =				SK.EL_ZEPHYR;
	SkillUnit[SU.UNT_POWER_OF_GAIA] =		SK.EL_POWER_OF_GAIA;
	SkillUnit[SU.UNT_FIRE_INSIGNIA] =		SK.SO_FIRE_INSIGNIA;
	SkillUnit[SU.UNT_WATER_INSIGNIA] =		SK.SO_WATER_INSIGNIA;
	SkillUnit[SU.UNT_WIND_INSIGNIA] =		SK.SO_WIND_INSIGNIA;
	SkillUnit[SU.UNT_EARTH_INSIGNIA] =		SK.SO_EARTH_INSIGNIA;
	SkillUnit[SU.UNT_POISON_MIST] =			SK.MH_POISON_MIST;
	SkillUnit[SU.UNT_LAVA_SLIDE] =			SK.MH_LAVA_SLIDE;
	SkillUnit[SU.UNT_VOLCANIC_ASH] =		SK.MH_VOLCANIC_ASH;
	SkillUnit[SU.UNT_ZENKAI_WATER] =		SK.KO_ZENKAI;
	SkillUnit[SU.UNT_MAKIBISHI] =			SK.KO_MAKIBISHI;
	SkillUnit[SU.UNT_VENOMFOG] =			SK.NPC_VENOMFOG;
	SkillUnit[SU.UNT_ICEMINE] =				SK.SC_SCAPE;
	SkillUnit[SU.UNT_MAGMA_ERUPTION] =		SK.NC_MAGMA_ERUPTION;
	SkillUnit[SU.UNT_B_TRAP] =				SK.RL_B_TRAP;

	return SkillUnit;
});
