window.ROConfigLocal = {  
    development: true,  
    remoteClient: 'https://grf.robrowser.com/',  
    servers: [  
        {  
            display: 'roBrowser Demo Server',  
            desc: 'demo server',  
            address: '127.0.0.1',  
            port: 6900,  
            version: 25,  
            langtype: 12,  
            packetver: 20130618,  
            renewal: false,  
            worldMapSettings: { episode: 12 },  
            packetKeys: false,  
            socketProxy: 'wss://connect.robrowser.com',  
            adminList: [2000000]  
        },  
        {  
            display: 'Ragna.ro',  
            desc: 'Ragna.ro [1/1/1] Renewal II',  
            address: 'ragna.ro',  
            port: 6900,  
            version: 30,  
            langtype: 240,  
            packetver: 20120410,  
            renewal: true,  
            worldMapSettings: { episode: 15 },  
            packetKeys: false,  
            socketProxy: 'wss://ragna.ro:5999',  
            remoteClient: 'https://client.ragna.ro/',  
            adminList: [2000000, 2000001],  
            FirstPersonCamera: true,  
            ThirdPersonCamera: true  
        },  
        {  
            display: 'NiktoutRO Chaos',  
            desc: 'NiktoutRO Chaos [100k/100k/10%]',  
            address: 'chaos.niktoutro.com',  
            port: 6905,  
            version: 55,  
            langtype: 1,  
            packetver: 20151104,  
            renewal: true,  
            socketProxy: 'wss://classicweb.niktoutro.com:5999',  
            remoteClient: 'https://classicweb.niktoutro.com/chaosclient/',  
            registrationweb: 'https://niktoutro.com/?module=account&action=create',  
            packetKeys: true,  
            adminList: [2000002]  
        }  
    ],  
    packetDump: false,  
    skipServerList: true,  
    skipIntro: false,  
    aura: {},  
    autoLogin: [],  
    BGMFileExtension: ['mp3'],  
    calculateHash: false,  
    CameraMaxZoomOut: 5,  
    charBlockSize: 0,  
    clientHash: null,  
    clientVersionMode: 'PacketVer',  
    disableConsole: false,  
    enableAchievements: false,
    enableBank: false,  
    enableCashShop: false,  
    enableCheckAttendance: false,  
    enableDmgSuffix: false,  
    enableHomunAutoFeed: false,  
    enableMapName: false,  
    FirstPersonCamera: false,  
    grfList: null,  
    hashFiles: [],  
    loadLua: false,  
    onReady: null,  
    plugins: {},  
    registrationweb: '',  
    saveFiles: true,  
    ThirdPersonCamera: false,  
    transitionDuration: 500  
};
